import sys
sys.stdout = open('log.txt', 'w')

ideas = [
"Instant Pot: Expectations vs. Reality",
"Will Cooking Ever Rule the World?",
"The Next Big Thing in Stories",
"Lessons Explained in Fewer than 140 Characters",
"This Week's Top Stories About Family",
"Where Will Instant Pot Be 1 Year From Now?",
"13 Things About Cooking You May Not Have Known",
"15 Things Your Boss Wishes You Knew About Stories",
"The Biggest Problem With Lessons, And How You Can Fix It",
"20 Up-and-Comers to Watch in the Family Industry",
"What NOT to Do in the Instant Pot Industry",
"14 Savvy Ways to Spend Leftover Cooking Budget",
"How to Sell Stories to a Skeptic",
"12 Reasons You Shouldn't Invest in Lessons",
"7 Little Changes That'll Make a Big Difference With Your Family",
"Meet the Steve Jobs of the Instant Pot Industry",
"What's Holding Back the Cooking Industry?",
"14 Common Misconceptions About Stories",
"16 Must-Follow Facebook Pages for Lessons Marketers",
"5 Cliches About Family You Should Avoid",
"10 Undeniable Reasons People Hate Instant Pot",
"10 Things We All Hate About Cooking",
"20 Resources That'll Make You Better at Stories",
"30 of the Punniest Lessons Puns You Can Find",
"Ask Me Anything: 10 Answers to Your Questions About Family",
"The 17 Most Misunderstood Facts About Instant Pot",
"10 Best Mobile Apps for Cooking",
"Stories Poll of the Day",
"7 Horrible Mistakes You're Making With Lessons",
"24 Hours to Improving Family",
"Why Nobody Cares About Instant Pot",
"How to Get Hired in the Cooking Industry",
"15 Secretly Funny People Working in Stories",
"15 Undeniable Reasons to Love Lessons",
"Think You're Cut Out for Doing Family? Take This Quiz",
"10 Compelling Reasons Why You Need Instant Pot",
"Addicted to Cooking? Us Too. 6 Reasons We Just Can't Stop",
"7 Things About Stories Your Boss Wants to Know",
"The Anatomy of a Great Lessons",
"10 Startups That'll Change the Family Industry for the Better",
"How to Win Big in the Instant Pot Industry",
"Responsible for a Cooking Budget? 12 Top Notch Ways to Spend Your Money",
"Why It's Easier to Succeed With Stories Than You Might Think",
"Why We Love Lessons (And You Should, Too!)",
"5 Real-Life Lessons About Family",
"11 Ways to Completely Revamp Your Instant Pot",
"Become an Expert on Cooking by Watching These 5 Videos",
"10 Things Everyone Hates About Stories",
"9 Signs You Need Help With Lessons",
"15 Best Twitter Accounts to Learn About Family",
"Forget Instant Pot: 3 Replacements You Need to Jump On",
"The Ultimate Cheat Sheet on Cooking",
"Why You Should Forget About Improving Your Stories",
"7 Answers to the Most Frequently Asked Questions About Lessons",
"20 Myths About Family: Busted",
"10 Things Your Competitors Can Teach You About Instant Pot",
"Cooking: What No One Is Talking About",
"20 Insightful Quotes About Stories",
"8 Go-To Resources About Lessons",
"15 Hilarious Videos About Family",
"15 Surprising Stats About Instant Pot",
"Why You Should Spend More Time Thinking About Cooking",
"12 Steps to Finding the Perfect Stories",
"10 Pinterest Accounts to Follow About Lessons",
"20 Fun Facts About Family",
"11 Ways to Completely Sabotage Your Instant Pot",
"Cooking: The Good, the Bad, and the Ugly",
"12 Do's and Don'ts for a Successful Stories",
"10 Principles of Psychology You Can Use to Improve Your Lessons",
"17 Signs You Work With Family",
"Watch Out: How Instant Pot Is Taking Over and What to Do About It",
"Cooking: It's Not as Difficult as You Think",
"How Technology Is Changing How We Treat Stories",
"5 Qualities the Best People in the Lessons Industry Tend to Have",
"10 Signs You Should Invest in Family",
"How to Solve Issues With Instant Pot",
"10 Things You Learned in Kindergarden That'll Help You With Cooking",
"10 Things Most People Don't Know About Stories",
"The Biggest Trends in Lessons We've Seen This Year",
"9 Signs You're a Family Expert",
"Don't Make This Silly Mistake With Your Instant Pot",
"15 Reasons Why You Shouldn't Ignore Cooking",
"The No. 1 Question Everyone Working in Stories Should Know How to Answer",
"15 Best Lessons Bloggers You Need to Follow",
"The Most Innovative Things Happening With Family",
"What Will Instant Pot Be Like in 100 Years?",
"17 Superstars We'd Love to Recruit for Our Cooking Team",
"An Introduction to Stories",
"How Much Should You Be Spending on Lessons?",
"15 Up-and-Coming Trends About Family",
"20 Things You Should Know About Instant Pot",
"11 Faux Pas That Are Actually Okay to Make With Your Cooking",
"The Worst Videos of All Time About Stories",
"The Worst Advice We've Ever Heard About Lessons",
"10 Things Steve Jobs Can Teach Us About Family",
"12 Companies Leading the Way in Instant Pot",
"How to Explain Cooking to Your Mom",
"5 Lessons About Stories You Can Learn From Superheroes",
"What Freud Can Teach Us About Lessons",
"7 Trends You May Have Missed About Family",
"6 Online Communities About Instant Pot You Should Join",
"Buzzwords, De-buzzed: 10 Other Ways to Say Cooking",
"What Sports Can Teach Us About Stories",
"Lessons: 11 Thing You're Forgetting to Do",
"The Top Reasons People Succeed in the Family Industry",
"A Beginner's Guide to Instant Pot",
"11 Creative Ways to Write About Cooking",
"The Most Influential People in the Stories Industry and Their Celebrity Dopplegangers",
"The Pros and Cons of Lessons",
"How Successful People Make the Most of Their Family",
"The Most Common Instant Pot Debate Isn't as Black and White as You Might Think",
"Your Worst Nightmare About Cooking Come to Life",
"5 Tools Everyone in the Stories Industry Should Be Using",
"Why the Biggest Myths About Lessons May Actually Be Right",
"30 Inspirational Quotes About Family",
"The 3 Greatest Moments in Instant Pot History",
"How to Get More Results Out of Your Cooking",
"10 Secrets About Stories You Can Learn From TV",
"The Advanced Guide to Lessons",
"Undeniable Proof That You Need Family",
"12 Stats About Instant Pot to Make You Look Smart Around the Water Cooler",
"Cooking: All the Stats, Facts, and Data You'll Ever Need to Know",
"Stories: A Simple Definition",
"What I Wish I Knew a Year Ago About Lessons",
"20 Trailblazers Leading the Way in Family",
"How to Save Money on Instant Pot",
"How Did We Get Here? The History of Cooking Told Through Tweets",
"How to Explain Stories to Your Grandparents",
"Getting Tired of Lessons? 10 Sources of Inspiration That'll Rekindle Your Love",
"15 Up-and-Coming Family Bloggers You Need to Watch",
"10 Apps to Help You Manage Your Instant Pot",
"14 Businesses Doing a Great Job at Cooking",
"The Stories Case Study You'll Never Forget",
"17 Reasons Why You Should Ignore Lessons",
"What the Best Family Pros Do (and You Should Too)",
"A Productive Rant About Instant Pot",
"20 Gifts You Can Give Your Boss if They Love Cooking",
"The 12 Worst Types Stories Accounts You Follow on Twitter",
"Will Lessons Ever Die?",
"Forget Family: 10 Reasons Why You No Longer Need It",
"From Around the Web: 20 Fabulous Infographics About Instant Pot",
"A Look Into the Future: What Will the Cooking Industry Look Like in 10 Years?",
"The Stories Awards: The Best, Worst, and Weirdest Things We've Seen",
"The Most Underrated Companies to Follow in the Lessons Industry",
"The 12 Best Family Accounts to Follow on Twitter",
"12 Helpful Tips For Doing Instant Pot",
"10 Facebook Pages to Follow About Cooking",
"5 Bad Habits That People in the Stories Industry Need to Quit",
"9 Signs You Sell Lessons for a Living",
"10 Meetups About Family You Should Attend",
"6 Books About Instant Pot You Should Read",
"10 Fundamentals About Cooking You Didn't Learn in School",
"The 13 Best Pinterest Boards for Learning About Stories",
"9 TED Talks That Anyone Working in Lessons Should Watch",
"3 Reasons Your Family Is Broken (And How to Fix It)",
"What Hollywood Can Teach Us About Instant Pot",
"15 Weird Hobbies That'll Make You Better at Cooking",
"15 Best Blogs to Follow About Stories",
"Everything You've Ever Wanted to Know About Lessons",
"Don't Buy Into These Trends About Family",
"10 Sites to Help You Become an Expert in Instant Pot",
"10 Facts About Cooking That Will Instantly Put You in a Good Mood",
"8 Videos About Stories That'll Make You Cry",
"How to Explain Lessons to Your Boss",
"Responsible for a Family Budget? 10 Terrible Ways to Spend Your Money",
"11 Embarrassing Instant Pot Faux Pas You Better Not Make",
"What Would the World Look Like Without Cooking?",
"Does Your Stories Pass The Test? 7 Things You Can Improve On Today",
"15 Terms Everyone in the Lessons Industry Should Know",
"Enough Already! 15 Things About Family We're Tired of Hearing",
"How to Explain Instant Pot to a Five-Year-Old",
"The Most Common Complaints About Cooking, and Why They're Bunk",
"The History of Stories",
"10 Inspirational Graphics About Lessons",
"How to Master Family in 6 Simple Steps",
"3 Common Reasons Why Your Instant Pot Isn't Working (And How To Fix It)",
"Is Tech Making Cooking Better or Worse?",
"A Stories Success Story You'll Never Believe",
"10 Quick Tips About Lessons",
"7 Things About Family You'll Kick Yourself for Not Knowing",
"Why You Should Focus on Improving Instant Pot",
"When Professionals Run Into Problems With Cooking, This Is What They Do",
"10 No-Fuss Ways to Figuring Out Your Stories",
"5 Laws That'll Help the Lessons Industry",
"The Ugly Truth About Family",
"Why You're Failing at Instant Pot",
"How to Outsmart Your Boss on Cooking",
"15 Tips About Stories From Industry Experts",
"10 Best Facebook Pages of All Time About Lessons",
"Where to Find Guest Blogging Opportunities on Family",
"11 Ways to Completely Ruin Your Instant Pot",
"10 Wrong Answers to Common Cooking Questions: Do You Know the Right Ones?",
"A Step-by-Step Guide to Stories",
"What the Oxford English Dictionary Doesn't Tell You About Lessons",
"20 Best Tweets of All Time About Family",
"15 Gifts for the Instant Pot Lover in Your Life",
"The Urban Dictionary of Cooking",
"15 Most Underrated Skills That'll Make You a Rockstar in the Stories Industry",
"The Intermediate Guide to Lessons",
"The Ultimate Glossary of Terms About Family",
"Instant Pot Explained in Instagram Photos",
"The Most Hilarious Complaints We've Heard About Cooking",
"The 3 Biggest Disasters in Stories History",
"Why People Love to Hate Lessons",
"14 Cartoons About Family That'll Brighten Your Day",
"A Trip Back in Time: How People Talked About Instant Pot 20 Years Ago",
"How to Outsmart Your Peers on Cooking",
"The Ultimate Checklist for Buying a Stories",
"The Worst Advice You Could Ever Get About Lessons",
"25 Surprising Facts About Family",
"10 Things You Learned in Preschool That'll Help You With Instant Pot",
"The Best Kept Secrets About Cooking",
"5 Killer Quora Answers on Stories",
"The Most Pervasive Problems in Lessons",
"Family: 10 Things I Wish I'd Known Earlier",
"10 Tips for Making a Good Instant Pot Even Better",
"20 Reasons You Need to Stop Stressing About Cooking",
"15 People You Oughta Know in the Stories Industry",
"So You've Bought Lessons ... Now What?",
"10 Celebrities Who Should Consider a Career in Family",
"How the 10 Worst Instant Pot Fails of All Time Could Have Been Prevented",
"From Around the Web: 20 Awesome Photos of Cooking",
"The Best Advice You Could Ever Get About Stories",
"5 Vines About Lessons That You Need to See",
"What the Heck Is Family?",
"10 Misconceptions Your Boss Has About Instant Pot",
"The Most Common Mistakes People Make With Cooking",
"The Most Influential People in the Stories Industry",
"What's the Current Job Market for Lessons Professionals Like?",
"The Ultimate Guide to Family",
"Are You Getting the Most Out of Your Instant Pot?",
"4 Dirty Little Secrets About the Cooking Industry",
"The Evolution of Stories",
"8 Effective Lessons Elevator Pitches",
"10 Tell-Tale Signs You Need to Get a New Family",
"5 Things Everyone Gets Wrong About Instant Pot",
"10 Situations When You'll Need to Know About Cooking",
"20 Questions You Should Always Ask About Stories Before Buying It",
"14 Questions You Might Be Afraid to Ask About Lessons",
"10 Great Family Public Speakers",
"9 Things Your Parents Taught You About Instant Pot",
"Everything You Need to Know About Cooking",
"How to Do Stories",
"How to Become an Expert at Lessons",
"What is Family and Why Does it Matter?",
"Common Mistakes of Instant Pot",
"3 Steps to Developing a Successful Cooking",
"5 Examples of Successful Stories",
"7 Recommended Tools to Build Lessons",
"10 Projects to Improve Your Family Skills",]

new_ideas = []
counter = 0
for idea in ideas:
  counter +=1
  placeholder_text = "{PLACEHOLDER}"
  placeholder = idea.replace("Cooking",placeholder_text).replace("Instant Pot:",placeholder_text).replace("Lessons",placeholder_text).replace("Stories",placeholder_text).replace("Family",placeholder_text)
  new_ideas.append(placeholder)


placeholders = ["Cooking","Alexa","Recipes"]

spark_ideas = []
for idea in new_ideas:
  for str in placeholders:
    spark_str = idea.replace(placeholder_text,str)
    spark_ideas.append(spark_str)

print(spark_ideas)

sys.stdout.close()
