ideas = [
"[placeholder]: Expectations vs. Reality",
"Will [placeholder] Ever Rule the World?",
"The Next Big Thing in [placeholder]",
"[placeholder] Explained in Fewer than 140 Characters",
"This Week's Top [placeholder] About [placeholder]",
"Where Will [placeholder] Be 1 Year From Now?",
"13 Things About [placeholder] You May Not Have Known",
"15 Things Your Boss Wishes You Knew About [placeholder]",
"The Biggest Problem With [placeholder], And How You Can Fix It",
"20 Up-and-Comers to Watch in the [placeholder] Industry",
"What NOT to Do in the [placeholder] Industry",
"14 Savvy Ways to Spend Leftover [placeholder] Budget",
"How to Sell [placeholder] to a Skeptic",
"12 Reasons You Shouldn't Invest in [placeholder]",
"7 Little Changes That'll Make a Big Difference With Your [placeholder]",
"Meet the Steve Jobs of the [placeholder] Industry",
"What's Holding Back the [placeholder] Industry?",
"14 Common Misconceptions About [placeholder]",
"16 Must-Follow Facebook Pages for [placeholder] Marketers",
"5 Cliches About [placeholder] You Should Avoid",
"10 Undeniable Reasons People Hate [placeholder]",
"10 Things We All Hate About [placeholder]",
"20 Resources That'll Make You Better at [placeholder]",
"30 of the Punniest [placeholder] Puns You Can Find",
"Ask Me Anything: 10 Answers to Your Questions About [placeholder]",
"The 17 Most Misunderstood Facts About [placeholder]",
"10 Best Mobile Apps for [placeholder]",
"[placeholder] Poll of the Day",
"7 Horrible Mistakes You're Making With [placeholder]",
"24 Hours to Improving [placeholder]",
"Why Nobody Cares About [placeholder]",
"How to Get Hired in the [placeholder] Industry",
"15 Secretly Funny People Working in [placeholder]",
"15 Undeniable Reasons to Love [placeholder]",
"Think You're Cut Out for Doing [placeholder]? Take This Quiz",
"10 Compelling Reasons Why You Need [placeholder]",
"Addicted to [placeholder]? Us Too. 6 Reasons We Just Can't Stop",
"7 Things About [placeholder] Your Boss Wants to Know",
"The Anatomy of a Great [placeholder]",
"10 Startups That'll Change the [placeholder] Industry for the Better",
"How to Win Big in the [placeholder] Industry",
"Responsible for a [placeholder] Budget? 12 Top Notch Ways to Spend Your Money",
"Why It's Easier to Succeed With [placeholder] Than You Might Think",
"Why We Love [placeholder] (And You Should, Too!)",
"5 Real-Life [placeholder] About [placeholder]",
"11 Ways to Completely Revamp Your [placeholder]",
"Become an Expert on [placeholder] by Watching These 5 Videos",
"10 Things Everyone Hates About [placeholder]",
"9 Signs You Need Help With [placeholder]",
"15 Best Twitter Accounts to Learn About [placeholder]",
"Forget [placeholder]: 3 Replacements You Need to Jump On",
"The Ultimate Cheat Sheet on [placeholder]",
"Why You Should Forget About Improving Your [placeholder]",
"7 Answers to the Most Frequently Asked Questions About [placeholder]",
"20 Myths About [placeholder]: Busted",
"10 Things Your Competitors Can Teach You About [placeholder]",
"[placeholder]: What No One Is Talking About",
"20 Insightful Quotes About [placeholder]",
"8 Go-To Resources About [placeholder]",
"15 Hilarious Videos About [placeholder]",
"15 Surprising Stats About [placeholder]",
"Why You Should Spend More Time Thinking About [placeholder]",
"12 Steps to Finding the Perfect [placeholder]",
"10 Pinterest Accounts to Follow About [placeholder]",
"20 Fun Facts About [placeholder]",
"11 Ways to Completely Sabotage Your [placeholder]",
"[placeholder]: The Good, the Bad, and the Ugly",
"12 Do's and Don'ts for a Successful [placeholder]",
"10 Principles of Psychology You Can Use to Improve Your [placeholder]",
"17 Signs You Work With [placeholder]",
"Watch Out: How [placeholder] Is Taking Over and What to Do About It",
"[placeholder]: It's Not as Difficult as You Think",
"How Technology Is Changing How We Treat [placeholder]",
"5 Qualities the Best People in the [placeholder] Industry Tend to Have",
"10 Signs You Should Invest in [placeholder]",
"How to Solve Issues With [placeholder]",
"10 Things You Learned in Kindergarden That'll Help You With [placeholder]",
"10 Things Most People Don't Know About [placeholder]",
"The Biggest Trends in [placeholder] We've Seen This Year",
"9 Signs You're a [placeholder] Expert",
"Don't Make This Silly Mistake With Your [placeholder]",
"15 Reasons Why You Shouldn't Ignore [placeholder]",
"The No. 1 Question Everyone Working in [placeholder] Should Know How to Answer",
"15 Best [placeholder] Bloggers You Need to Follow",
"The Most Innovative Things Happening With [placeholder]",
"What Will [placeholder] Be Like in 100 Years?",
"17 Superstars We'd Love to Recruit for Our [placeholder] Team",
"An Introduction to [placeholder]",
"How Much Should You Be Spending on [placeholder]?",
"15 Up-and-Coming Trends About [placeholder]",
"20 Things You Should Know About [placeholder]",
"11 Faux Pas That Are Actually Okay to Make With Your [placeholder]",
"The Worst Videos of All Time About [placeholder]",
"The Worst Advice We've Ever Heard About [placeholder]",
"10 Things Steve Jobs Can Teach Us About [placeholder]",
"12 Companies Leading the Way in [placeholder]",
"How to Explain [placeholder] to Your Mom",
"5 [placeholder] About [placeholder] You Can Learn From Superheroes",
"What Freud Can Teach Us About [placeholder]",
"7 Trends You May Have Missed About [placeholder]",
"6 Online Communities About [placeholder] You Should Join",
"Buzzwords, De-buzzed: 10 Other Ways to Say [placeholder]",
"What Sports Can Teach Us About [placeholder]",
"[placeholder]: 11 Thing You're Forgetting to Do",
"The Top Reasons People Succeed in the [placeholder] Industry",
"A Beginner's Guide to [placeholder]",
"11 Creative Ways to Write About [placeholder]",
"The Most Influential People in the [placeholder] Industry and Their Celebrity Dopplegangers",
"The Pros and Cons of [placeholder]",
"How Successful People Make the Most of Their [placeholder]",
"The Most Common [placeholder] Debate Isn't as Black and White as You Might Think",
"Your Worst Nightmare About [placeholder] Come to Life",
"5 Tools Everyone in the [placeholder] Industry Should Be Using",
"Why the Biggest Myths About [placeholder] May Actually Be Right",
"30 Inspirational Quotes About [placeholder]",
"The 3 Greatest Moments in [placeholder] History",
"How to Get More Results Out of Your [placeholder]",
"10 Secrets About [placeholder] You Can Learn From TV",
"The Advanced Guide to [placeholder]",
"Undeniable Proof That You Need [placeholder]",
"12 Stats About [placeholder] to Make You Look Smart Around the Water Cooler",
"[placeholder]: All the Stats, Facts, and Data You'll Ever Need to Know",
"[placeholder]: A Simple Definition",
"What I Wish I Knew a Year Ago About [placeholder]",
"20 Trailblazers Leading the Way in [placeholder]",
"How to Save Money on [placeholder]",
"How Did We Get Here? The History of [placeholder] Told Through Tweets",
"How to Explain [placeholder] to Your Grandparents",
"Getting Tired of [placeholder]? 10 Sources of Inspiration That'll Rekindle Your Love",
"15 Up-and-Coming [placeholder] Bloggers You Need to Watch",
"10 Apps to Help You Manage Your [placeholder]",
"14 Businesses Doing a Great Job at [placeholder]",
"The [placeholder] Case Study You'll Never Forget",
"17 Reasons Why You Should Ignore [placeholder]",
"What the Best [placeholder] Pros Do (and You Should Too)",
"A Productive Rant About [placeholder]",
"20 Gifts You Can Give Your Boss if They Love [placeholder]",
"The 12 Worst Types [placeholder] Accounts You Follow on Twitter",
"Will [placeholder] Ever Die?",
"Forget [placeholder]: 10 Reasons Why You No Longer Need It",
"From Around the Web: 20 Fabulous Infographics About [placeholder]",
"A Look Into the Future: What Will the [placeholder] Industry Look Like in 10 Years?",
"The [placeholder] Awards: The Best, Worst, and Weirdest Things We've Seen",
"The Most Underrated Companies to Follow in the [placeholder] Industry",
"The 12 Best [placeholder] Accounts to Follow on Twitter",
"12 Helpful Tips For Doing [placeholder]",
"10 Facebook Pages to Follow About [placeholder]",
"5 Bad Habits That People in the [placeholder] Industry Need to Quit",
"9 Signs You Sell [placeholder] for a Living",
"10 Meetups About [placeholder] You Should Attend",
"6 Books About [placeholder] You Should Read",
"10 Fundamentals About [placeholder] You Didn't Learn in School",
"The 13 Best Pinterest Boards for Learning About [placeholder]",
"9 TED Talks That Anyone Working in [placeholder] Should Watch",
"3 Reasons Your [placeholder] Is Broken (And How to Fix It)",
"What Hollywood Can Teach Us About [placeholder]",
"15 Weird Hobbies That'll Make You Better at [placeholder]",
"15 Best Blogs to Follow About [placeholder]",
"Everything You've Ever Wanted to Know About [placeholder]",
"Don't Buy Into These Trends About [placeholder]",
"10 Sites to Help You Become an Expert in [placeholder]",
"10 Facts About [placeholder] That Will Instantly Put You in a Good Mood",
"8 Videos About [placeholder] That'll Make You Cry",
"How to Explain [placeholder] to Your Boss",
"Responsible for a [placeholder] Budget? 10 Terrible Ways to Spend Your Money",
"11 Embarrassing [placeholder] Faux Pas You Better Not Make",
"What Would the World Look Like Without [placeholder]?",
"Does Your [placeholder] Pass The Test? 7 Things You Can Improve On Today",
"15 Terms Everyone in the [placeholder] Industry Should Know",
"Enough Already! 15 Things About [placeholder] We're Tired of Hearing",
"How to Explain [placeholder] to a Five-Year-Old",
"The Most Common Complaints About [placeholder], and Why They're Bunk",
"The History of [placeholder]",
"10 Inspirational Graphics About [placeholder]",
"How to Master [placeholder] in 6 Simple Steps",
"3 Common Reasons Why Your [placeholder] Isn't Working (And How To Fix It)",
"Is Tech Making [placeholder] Better or Worse?",
"A [placeholder] Success Story You'll Never Believe",
"10 Quick Tips About [placeholder]",
"7 Things About [placeholder] You'll Kick Yourself for Not Knowing",
"Why You Should Focus on Improving [placeholder]",
"When Professionals Run Into Problems With [placeholder], This Is What They Do",
"10 No-Fuss Ways to Figuring Out Your [placeholder]",
"5 Laws That'll Help the [placeholder] Industry",
"The Ugly Truth About [placeholder]",
"Why You're Failing at [placeholder]",
"How to Outsmart Your Boss on [placeholder]",
"15 Tips About [placeholder] From Industry Experts",
"10 Best Facebook Pages of All Time About [placeholder]",
"Where to Find Guest Blogging Opportunities on [placeholder]",
"11 Ways to Completely Ruin Your [placeholder]",
"10 Wrong Answers to Common [placeholder] Questions: Do You Know the Right Ones?",
"A Step-by-Step Guide to [placeholder]",
"What the Oxford English Dictionary Doesn't Tell You About [placeholder]",
"20 Best Tweets of All Time About [placeholder]",
"15 Gifts for the [placeholder] Lover in Your Life",
"The Urban Dictionary of [placeholder]",
"15 Most Underrated Skills That'll Make You a Rockstar in the [placeholder] Industry",
"The Intermediate Guide to [placeholder]",
"The Ultimate Glossary of Terms About [placeholder]",
"[placeholder] Explained in Instagram Photos",
"The Most Hilarious Complaints We've Heard About [placeholder]",
"The 3 Biggest Disasters in [placeholder] History",
"Why People Love to Hate [placeholder]",
"14 Cartoons About [placeholder] That'll Brighten Your Day",
"A Trip Back in Time: How People Talked About [placeholder] 20 Years Ago",
"How to Outsmart Your Peers on [placeholder]",
"The Ultimate Checklist for Buying a [placeholder]",
"The Worst Advice You Could Ever Get About [placeholder]",
"25 Surprising Facts About [placeholder]",
"10 Things You Learned in Preschool That'll Help You With [placeholder]",
"The Best Kept Secrets About [placeholder]",
"5 Killer Quora Answers on [placeholder]",
"The Most Pervasive Problems in [placeholder]",
"[placeholder]: 10 Things I Wish I'd Known Earlier",
"10 Tips for Making a Good [placeholder] Even Better",
"20 Reasons You Need to Stop Stressing About [placeholder]",
"15 People You Oughta Know in the [placeholder] Industry",
"So You've Bought [placeholder] ... Now What?",
"10 Celebrities Who Should Consider a Career in [placeholder]",
"How the 10 Worst [placeholder] Fails of All Time Could Have Been Prevented",
"From Around the Web: 20 Awesome Photos of [placeholder]",
"The Best Advice You Could Ever Get About [placeholder]",
"5 Vines About [placeholder] That You Need to See",
"What the Heck Is [placeholder]?",
"10 Misconceptions Your Boss Has About [placeholder]",
"The Most Common Mistakes People Make With [placeholder]",
"The Most Influential People in the [placeholder] Industry",
"What's the Current Job Market for [placeholder] Professionals Like?",
"The Ultimate Guide to [placeholder]",
"Are You Getting the Most Out of Your [placeholder]?",
"4 Dirty Little Secrets About the [placeholder] Industry",
"The Evolution of [placeholder]",
"8 Effective [placeholder] Elevator Pitches",
"10 Tell-Tale Signs You Need to Get a New [placeholder]",
"5 Things Everyone Gets Wrong About [placeholder]",
"10 Situations When You'll Need to Know About [placeholder]",
"20 Questions You Should Always Ask About [placeholder] Before Buying It",
"14 Questions You Might Be Afraid to Ask About [placeholder]",
"10 Great [placeholder] Public Speakers",
"9 Things Your Parents Taught You About [placeholder]",
"Everything You Need to Know About [placeholder]",
"How to Do [placeholder]",
"How to Become an Expert at [placeholder]",
"What is [placeholder] and Why Does it Matter?",
"Common Mistakes of [placeholder]",
"3 Steps to Developing a Successful [placeholder]",
"5 Examples of Successful [placeholder]",
"7 Recommended Tools to Build [placeholder]",
"10 Projects to Improve Your [placeholder] Skills"]